#!/bin/bash
# src: https://github.com/Jakehp/bromit
# cmd: git-bromit
# desc: http://i.imgur.com/pVNPOtA.png

bro[0]='#yoco'
bro[1]='code has been slingd'
bro[2]='pushed; lets collab'
bro[3]='someone do me a solid and clean this up'
bro[4]='ultimate frisbee anyone?'
bro[5]='dev city right here'
bro[6]='dave matthews is in town, committing and heading out'
bro[7]='diff and learn'
bro[8]='end of hack sesh'
bro[9]='added some broutines'
bro[10]='ruby could have done this in 1 line'
bro[11]='@#SXSW, live push'
bro[12]='crushd out some functions'
bro[13]='test it in production'
bro[14]='#BOMBSAWAY'
bro[15]='dont pull just yet this is broke'
bro[16]='implementd'
bro[17]='commit it and quit it'
bro[18]='fixed some features'
bro[19]='bro, do you even git?'
bro[20]='cool story, scrumbro'
bro[21]='i commit to github, not girls'
bro[22]='pumping iron and code'
bro[23]='sudo apt-get remove yourcode'
bro[24]='ror4lyfe'
bro[25]='flippin bits'
bro[26]='refactoring to objective-c'
bro[27]='CI -ignore -m perfect'
bro[28]='brosigned some new classes'
bro[29]='switching to ruby; java has no ecosystem'

arraySize=${#bro[@]}
rand=$(($RANDOM % $arraySize))
randBromit=${bro[${rand}]}
git commit -m "$randBromit"
echo $randBromit
